### ISSUE TITLE
error in iocage create command

### ISSUE THREAD

**Issue by HackInTheBox** [basilhendroff/truenas-iocage-letsencrypt#6]
https://github.com/basilhendroff/truenas-iocage-letsencrypt/blob/c8210367d9288724274c722e8b4f06a9640f3088/le-jail.sh#L103

ip4_addr="${INTERFACE}|${JAIL_IP}/${NETMASK}"

should be

ip4_addr="${INTERFACE}|${IP}/${NETMASK}"

**Comment by basilhendroff** [comment]
Fixed! Thanks for the feedback!
